name: Shopify CLI
description: "Run the Shopify CLI in a GitHub Actions CI environment."
inputs: 
  command: 
    description: "The command to execute"
    required: true
  path: 
    description: "Relative path of a folder to run the command"
    required: false
runs: 
  main: index.js
  using: node12