name: shopify-cli-action

env:
  SHOPIFY_CLI_ACTION_DEVELOPMENT: "1"

up:
  - node:
      yarn: true
      version: v16.13.0
      packages:
        - ./

test:
  desc: "Run tests."
  run: yarn run test

commands:
  format:
    run: yarn run format
