name: shopify-cli-action

env:
  SHOPIFY_CLI_ACTION_DEVELOPMENT: "1"

up:
  - node:
      yarn: true
      version: v16.13.0
      packages:
        - ./

test:
  desc: "Run tests."
  run: |
    if [ "$#" -eq 1 ] && [[ -f $1 ]];
    then
      bundle exec rake test TEST=$1
    else
      bundle exec rake test $@
    fi

commands:
  style:
    run: bundle exec rubocop .
